-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema myDeweyDecimalSystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myDeweyDecimalSystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myDeweyDecimalSystem` DEFAULT CHARACTER SET utf8 ;
USE `myDeweyDecimalSystem` ;

-- -----------------------------------------------------
-- Table `myDeweyDecimalSystem`.`dewey_struct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myDeweyDecimalSystem`.`dewey_struct` ;

CREATE TABLE IF NOT EXISTS `myDeweyDecimalSystem`.`dewey_struct` (
  `code` INT NOT NULL,
  `name` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myDeweyDecimalSystem`.`document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myDeweyDecimalSystem`.`document` ;

CREATE TABLE IF NOT EXISTS `myDeweyDecimalSystem`.`document` (
  `iddocument` INT NOT NULL AUTO_INCREMENT,
  `sub_div` VARCHAR(200) NULL,
  `create_at` DATE NULL,
  `dewey_struct_code` INT NOT NULL,
  PRIMARY KEY (`iddocument`),
  INDEX `fk_document_dewey_struct1_idx` (`dewey_struct_code` ASC),
  CONSTRAINT `fk_document_dewey_struct1`
    FOREIGN KEY (`dewey_struct_code`)
    REFERENCES `myDeweyDecimalSystem`.`dewey_struct` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myDeweyDecimalSystem`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myDeweyDecimalSystem`.`book` ;

CREATE TABLE IF NOT EXISTS `myDeweyDecimalSystem`.`book` (
  `isbn` VARCHAR(50) NOT NULL,
  `title` VARCHAR(300) NULL,
  `url` VARCHAR(300) NULL,
  `edition` VARCHAR(45) NULL,
  `publisher_name` VARCHAR(200) NULL,
  `iddocument` INT NOT NULL,
  PRIMARY KEY (`isbn`),
  INDEX `fk_book_document1_idx` (`iddocument` ASC),
  CONSTRAINT `fk_book_document1`
    FOREIGN KEY (`iddocument`)
    REFERENCES `myDeweyDecimalSystem`.`document` (`iddocument`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myDeweyDecimalSystem`.`author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myDeweyDecimalSystem`.`author` ;

CREATE TABLE IF NOT EXISTS `myDeweyDecimalSystem`.`author` (
  `idauthor` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idauthor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myDeweyDecimalSystem`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myDeweyDecimalSystem`.`post` ;

CREATE TABLE IF NOT EXISTS `myDeweyDecimalSystem`.`post` (
  `idpost` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(150) NULL,
  `content` MEDIUMTEXT NULL,
  `type` VARCHAR(45) NULL,
  `book_isbn` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idpost`),
  INDEX `fk_post_book1_idx` (`book_isbn` ASC),
  CONSTRAINT `fk_post_book1`
    FOREIGN KEY (`book_isbn`)
    REFERENCES `myDeweyDecimalSystem`.`book` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myDeweyDecimalSystem`.`book_has_author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myDeweyDecimalSystem`.`book_has_author` ;

CREATE TABLE IF NOT EXISTS `myDeweyDecimalSystem`.`book_has_author` (
  `book_isbn` VARCHAR(50) NOT NULL,
  `author_idauthor` INT NOT NULL,
  INDEX `fk_book_has_author_book1_idx` (`book_isbn` ASC),
  INDEX `fk_book_has_author_author1_idx` (`author_idauthor` ASC),
  PRIMARY KEY (`book_isbn`, `author_idauthor`),
  CONSTRAINT `fk_book_has_author_book1`
    FOREIGN KEY (`book_isbn`)
    REFERENCES `myDeweyDecimalSystem`.`book` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_has_author_author1`
    FOREIGN KEY (`author_idauthor`)
    REFERENCES `myDeweyDecimalSystem`.`author` (`idauthor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- >>>>>>>>>>>>>>>>>>>>>>>>>>>> CREATE VIEWS >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

CREATE OR REPLACE VIEW v_authors AS
	(SELECT bha.book_isbn as isbn, GROUP_CONCAT(name) as authors FROM author
    JOIN book_has_author bha
    ON bha.author_idauthor = author.idauthor
    GROUP BY bha.book_isbn);
    
CREATE OR REPLACE VIEW v_doc_by_dewey AS
	(SELECT d.iddocument, d.sub_div, d.create_at, ds.code as dewey_code, ds.name as dewey_name  FROM document d
    LEFT JOIN dewey_struct ds
    ON ds.code = d.dewey_struct_code
    GROUP BY d.iddocument);
    
CREATE OR REPLACE VIEW v_book_authors AS
	(SELECT b.iddocument, b.isbn, b.title, v_a.authors, b.url, b.edition, b.publisher_name FROM book b
    JOIN v_authors v_a
    ON v_a.isbn = b.isbn
    GROUP BY b.isbn);    
    
CREATE OR REPLACE VIEW v_book AS
	(SELECT vba.isbn, vba.title, vba.authors, vba.url, vba.edition, vba.publisher_name, vdd.dewey_code, vdd.dewey_name, vdd.sub_div FROM v_book_authors vba
    JOIN v_doc_by_dewey vdd
    ON vdd.iddocument = vba.iddocument
    GROUP BY vba.isbn);
   
-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- >>>>>>>>>>>>>>>>>>>>>>>> End of CREATE VIEWS >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

insert into dewey_struct (code, name) values
  (0, "Computer science"),
  (1, "Knowledge"),
  (2, "The book"),
  (3, "Systems"),
  (4, "Data processing & computer science"),
  (5, "Computer programming, programs & data"),
  (6, "Special computer methods"),
  (10, "Bibliographies"),
  (12, "Bibliographies of individuals"),
  (14, "Bibliographies of anonymous & pseudonymous works"),
  (15, "Bibliographies of works from specific places"),
  (16, "Bibliographies of works on specific subjects"),
  (17, "General subject catalogs"),
  (18, "Catalogs arranged by author, date, etc."),
  (19, "Dictionary catalogs"),
  (20, "Library & information sciences"),
  (21, "Library relationships (with archives, information centers, etc.)"),
  (22, "Administration of physical plant"),
  (23, "Personnel management"),
  (25, "Library operations"),
  (26, "Libraries for specific subjects"),
  (27, "General libraries"),
  (28, "Reading & use of other information media"),
  (30, "General encyclopedic works"),
  (31, "Encyclopedias in American English"),
  (32, "Encyclopedias in English"),
  (33, "Encyclopedias in other Germanic languages"),
  (34, "Encyclopedias in French, Occitan, and Catalan"),
  (35, "Encyclopedias in Italian, Romanian, and related languages"),
  (36, "Encyclopedias in Spanish & Portuguese"),
  (37, "Encyclopedias in Slavic languages"),
  (38, "Encyclopedias in Scandinavian languages"),
  (39, "Encyclopedias in other languages"),
  (40, "[Unassigned]"), 
  (50, "Magazines, journals & serials"),
  (51, "Serials in American English"),
  (52, "Serials in English"),
  (53, "Serials in other Germanic languages"),
  (54, "Serials in French, Occitan, and Catalan"),
  (55, "Serials in Italian, Romanian, and related languages"),
  (56, "Serials in Spanish & Portuguese"),
  (57, "Serials in Slavic languages"),
  (58, "Serials in Scandinavian languages"),
  (59, "Serials in other languages"),
  (60, "General organizations & museums"),
  (61, "Organizations in North America"),
  (62, "Organizations in British Isles; in England"),
  (63, "Organizations in central Europe; in Germany"),
  (64, "Organizations in France & Monaco"),
  (65, "Organizations in Italy & adjacent islands"),
  (66, "Organizations in Iberian peninsula & adjacent islands"),
  (67, "Organizations in eastern Europe; in Russia"),
  (68, "Organizations in other geographic areas"),
  (69, "Museum science"),
  (70, "News media, journalism, and publishing"),
  (71, "Newspapers in North America"),
  (72, "Newspapers in British Isles; in England"),
  (73, "Newspapers in central Europe; in Germany"),
  (74, "Newspapers in France & Monaco"),
  (75, "Newspapers in Italy & adjacent islands"),
  (76, "Newspapers in Iberian peninsula & adjacent islands"),
  (77, "Newspapers in eastern Europe; in Russia"),
  (78, "Newspapers in Scandinavia"),
  (79, "Newspapers in other geographic areas"),
  (80, "Quotations"),
  (81, "Collections in American English"),
  (82, "Collections in English"),
  (83, "Collections in other Germanic languages"),
  (84, "Collections in French, Occitan, Catalan"),
  (85, "Collections in Italian, Romanian, and related languages"),
  (86, "Collections in Spanish & Portuguese"),
  (87, "Collections in Slavic languages"),
  (88, "Collections in Scandinavian languages"),
  (89, "Collections in other languages"),
  (90, "Manuscripts and rare books"),
  (91, "Manuscripts"),
  (92, "Block books"),
  (93, "Incunabula"),
  (94, "Printed books"),
  (95, "Books notable for bindings"),
  (96, "Books notable for illustrations"),
  (97, "Books notable for ownership or origin"),
  (98, "Prohibited works, forgeries, and hoaxes"),
  (99, "Books notable for format"),
  (100, "Philosophy"),
  (101, "Manuscripts and rare books/Theory of philosophy"),
  (102, "Manuscripts and rare books/Miscellany"),
  (103, "Manuscripts and rare books/Dictionaries & encyclopedias"),
  (105, "Manuscripts and rare books/Serial publications"),
  (106, "Manuscripts and rare books/Organizations & management"),
  (107, "Manuscripts and rare books/Education, research, related topics of philosophy"),
  (108, "Manuscripts and rare books/Groups of people"),
  (109, "Manuscripts and rare books/History & collected biography"),
  (110, "Metaphysics"),
  (111, "Ontology"),
  (113, "Cosmology (Philosophy of nature)"),
  (114, "Space"),
  (115, "Time"),
  (116, "Change"),
  (117, "Structure"),
  (118, "Force and energy"),
  (119, "Number and quantity"),
  (120, "Epistemology"),
  (121, "Epistemology (Theory of knowledge)"),
  (122, "Causation"),
  (123, "Determinism and indeterminism"),
  (124, "Teleology"),
  (126, "The self"),
  (127, "The unconscious & the subconscious"),
  (128, "Humankind"),
  (129, "Origin & destiny of individual souls"),
  (130, "Parapsychology & occultism"),
  (131, "Parapsychological and occult methods for achieving well-being, happiness, success"),
  (133, "Specific topics in parapsychology & occultism"),
  (135, "Dreams & mysteries"),
  (137, "Divinatory graphology"),
  (138, "Physiognomy"),
  (139, "Phrenology"),
  (140, "Philosophical schools of thought"),
  (141, "Idealism & related systems & doctrines"),
  (142, "Critical philosophy"),
  (143, "Bergsonism & intuitionism"),
  (144, "Humanism & related systems & doctrines"),
  (145, "Sensationalism"),
  (146, "Naturalism & related systems & doctrines"),
  (147, "Pantheism & related systems & doctrines"),
  (148, "Dogmatism, eclecticism, liberalism, syncretism, & traditionalism"),
  (149, "Other philosophical systems & doctrines"),
  (150, "Psychology"),
  (152, "Sensory perception, movement, emotions, & physiological drives"),
  (153, "Conscious mental processes & intelligence"),
  (154, "Subconscious & altered states & processes"),
  (155, "Differential & developmental psychology"),
  (156, "Comparative psychology"),
  (158, "Applied psychology"),
  (160, "Philosophical logic"),
  (161, "Induction"),
  (162, "Deduction"),
  (165, "Fallacies & sources of error"),
  (166, "Syllogisms"),
  (167, "Hypotheses"),
  (168, "Argument & persuasion"),
  (169, "Analogy"),
  (170, "Ethics"),
  (171, "Ethical systems"),
  (172, "Political ethics"),
  (173, "Ethics of family relationships"),
  (174, "Occupational ethics"),
  (175, "Ethics of recreation, leisure, public performances, communication"),
  (176, "Ethics of sex & reproduction"),
  (177, "Ethics of social relations"),
  (178, "Ethics of consumption"),
  (179, "Other ethical norms"),
  (180, "Ancient, medieval, & Eastern philosophy"),
  (181, "Eastern philosophy"),
  (182, "Pre-Socratic Greek philosophies"),
  (183, "Sophistic, Socratic, related Greek philosophies"),
  (184, "Platonic philosophy"),
  (185, "Aristotelian philosophy"),
  (186, "Skeptic & Neoplatonic philosophies"),
  (187, "Epicurean philosophy"),
  (188, "Stoic philosophy"),
  (189, "Medieval Western philosophy"),
  (190, "Modern Western Philosophy"),
  (191, "Philosophy of the United States and Canada"),
  (192, "Philosophy of the British Isles"),
  (193, "Philosophy of Germany and Austria"),
  (194, "Philosophy of France"),
  (195, "Philosophy of Italy"),
  (196, "Philosophy of Spain and Portugal"),
  (197, "Philosophy of Russia"),
  (198, "Philosophy of Scandinavia & Finland"),
  (199, "Philosophy in other geographic areas"),
  (200, "Religion"),
  (201, "Modern Western philosophy (19th-century, 20th-century)"),
  (202, "Modern Western philosophy (19th-century, 20th-century)/Doctrines"),
  (203, "Modern Western philosophy (19th-century, 20th-century)/Public worship and other practices"),
  (204, "Modern Western philosophy (19th-century, 20th-century)/Religious experience, life, practice"),
  (205, "Modern Western philosophy (19th-century, 20th-century)/Religious ethics"),
  (206, "Modern Western philosophy (19th-century, 20th-century)/Leaders and organization"),
  (207, "Modern Western philosophy (19th-century, 20th-century)/Missions and religious education"),
  (208, "Modern Western philosophy (19th-century, 20th-century)/Sources"),
  (209, "Modern Western philosophy (19th-century, 20th-century)/Sects and reform movements"),
  (210, "Philosophy & theory of religion"),
  (211, "Concepts of God"),
  (212, "Existence, ways of knowing God, attributes of God"),
  (213, "Creation"),
  (214, "Theodicy"),
  (215, "Science & religion"),
  (218, "Humankind"),
  (220, "The Bible"),
  (221, "Old Testament (Tanakh)"),
  (222, "Historical books of Old Testament"),
  (223, "Poetic books of Old Testament"),
  (224, "Prophetic books of Old Testament"),
  (225, "New Testament"),
  (226, "Gospels & Acts"),
  (227, "Epistles"),
  (228, "Revelation (Apocalypse)"),
  (229, "Apocrypha, pseudepigrapha, & intertestamental works"),
  (230, "Christianity"),
  (231, "God"),
  (232, "Jesus Christ & his family"),
  (233, "Humankind"),
  (234, "Salvation & grace"),
  (235, "Spiritual beings"),
  (236, "Eschatology"),
  (238, "Creeds, confessions of faith, covenants, & catechisms"),
  (239, "Apologetics & polemics"),
  (240, "Christian practice & observance"),
  (241, "Christian ethics"),
  (242, "Devotional literature"),
  (243, "Evangelistic writings for individuals and families"),
  (246, "Use of art in Christianity"),
  (247, "Church furnishings & related articles"),
  (248, "Christian experience, practice, life"),
  (249, "Christian observances in family life"),
  (250, "Christian pastoral practice & religious orders"),
  (251, "Preaching (Homiletics)"),
  (252, "Texts of sermons"),
  (253, "Pastoral office and work (Pastoral theology)"),
  (254, "Parish administration"),
  (255, "Religious congregations & orders"),
  (259, "Pastoral care of families, of specific groups of people"),
  (260, "Christian social and ecclesiastical theology"),
  (261, "Social theology and interreligious relations and attitudes"),
  (262, "Ecclesiology"),
  (263, "Days, times, places of religious observance"),
  (264, "Public worship"),
  (265, "Sacraments, other rites & acts"),
  (266, "Missions"),
  (267, "Associations for religious work"),
  (268, "Religious education"),
  (269, "Spiritual renewal"),
  (270, "History of Christianity"),
  (271, "Religious congregations and orders in church history"),
  (272, "Persecutions in church history"),
  (273, "Doctrinal controversies and heresies in general church history"),
  (274, "Christianity in Europe"),
  (275, "Christianity in Asia"),
  (276, "Christianity in Africa"),
  (277, "Christianity in North America"),
  (278, "Christianity in South America"),
  (279, "History of Christianity in other areas"),
  (280, "Christian denominations"),
  (281, "Early church & Eastern churches"),
  (282, "Roman Catholic Church"),
  (283, "Anglican churches"),
  (284, "Protestant denominations of Continental origin & related body"),
  (285, "Presbyterian churches, Reformed churches centered in America, Congregational churches"),
  (286, "Baptist, Restoration Movement, Adventist churches"),
  (287, "Methodist churches; churches related to Methodism"),
  (289, "Other denominations & sects"),
  (290, "Other religions"),
  (292, "Classical religion (Greek & Roman religion)"),
  (293, "Germanic religion"),
  (294, "Religions of Indic origin"),
  (295, "Zoroastrianism (Mazdaism, Parseeism)"),
  (296, "Judaism"),
  (297, "Islam, Bábism & Bahá'í Faith"),
  (299, "Religions not provided for elsewhere"),
  (300, "Social sciences, sociology & anthropology"),
  (301, "Other religions/Sociology & anthropology"),
  (302, "Other religions/Social interaction"),
  (303, "Other religions/Social processes"),
  (304, "Other religions/Factors affecting social behavior"),
  (305, "Other religions/Groups of people"),
  (306, "Other religions/Culture & institutions"),
  (307, "Other religions/Communities"),
  (310, "Statistics"),
  (314, "General statistics of Europe"),
  (315, "General statistics of Asia"),
  (316, "General statistics of Africa"),
  (317, "General statistics of North America"),
  (318, "General statistics of South America"),
  (319, "General statistics of Australasia, Pacific Ocean islands, Atlantic Ocean islands, Arctic islands, Antarctica"),
  (320, "Political science"),
  (321, "Systems of governments & states"),
  (322, "Relation of state to organized groups & their members"),
  (323, "Civil & political rights"),
  (324, "The political process"),
  (325, "International migration & colonization"),
  (326, "Slavery & emancipation"),
  (327, "International relations"),
  (328, "The legislative process"),
  (330, "Economics"),
  (331, "Labor economics"),
  (332, "Financial economics"),
  (333, "Economics of land & energy"),
  (334, "Cooperatives"),
  (335, "Socialism & related systems"),
  (336, "Public finance"),
  (337, "International economics"),
  (338, "Production"),
  (339, "Macroeconomics & related topics"),
  (340, "Law"),
  (341, "Law of nations"),
  (342, "Constitutional & administrative law"),
  (343, "Military, defense, public property, public finance, tax, commerce (trade, industrial law)"),
  (344, "Labor, social service, education, cultural law"),
  (345, "Criminal law"),
  (346, "Private law"),
  (347, "Procedure & courts"),
  (348, "Laws, regulations, cases"),
  (349, "Law of specific jurisdictions, areas, socioeconomic regions, regional intergovernmental organizations"),
  (350, "Public administration & military science"),
  (351, "Public administration"),
  (352, "General considerations of public administration"),
  (353, "Specific fields of public administration"),
  (354, "Public administration of economy & environment"),
  (355, "Military science"),
  (356, "Foot forces & warfare"),
  (357, "Mounted forces & warfare"),
  (358, "Air & other specialized forces & warfare; engineering & related services"),
  (359, "Sea forces & warfare"),
  (360, "Social problems & social services"),
  (361, "Social problems & services"),
  (362, "Social problems of & services to groups of people"),
  (363, "Other social problems & services"),
  (364, "Criminology"),
  (365, "Penal & related institutions"),
  (366, "Secret associations & societies"),
  (367, "General clubs"),
  (368, "Insurance"),
  (369, "Associations"),
  (370, "Education"),
  (371, "Schools & their activities; special education"),
  (372, "Primary education (elementary education)"),
  (373, "Secondary education"),
  (374, "Adult education"),
  (375, "Curricula"),
  (378, "Higher education (Tertiary education)"),
  (379, "Public policy issues in education"),
  (380, "Commerce, communications, transportation"),
  (381, "Commerce (Trade)"),
  (382, "International commerce (Foreign trade)"),
  (383, "Postal communication"),
  (384, "Communications"),
  (385, "Railroad transportation"),
  (386, "Inland waterway & ferry transportation"),
  (387, "Water, air, space transportation"),
  (388, "Transportation"),
  (389, "Metrology & standardization"),
  (390, "Customs, etiquette, folklore"),
  (391, "Costume & personal appearance"),
  (392, "Customs of life cycle & domestic life"),
  (393, "Death customs"),
  (394, "General customs"),
  (395, "Etiquette (Manners)"),
  (398, "Folklore"),
  (399, "Customs of war & diplomacy"),
  (400, "Language"),
  (401, "Customs, etiquette, folklore/Philosophy & theory; international languages"),
  (402, "Customs, etiquette, folklore/Miscellany"),
  (403, "Customs, etiquette, folklore/Dictionaries, encyclopedias, concordances"),
  (404, "Customs, etiquette, folklore/Special topics of language"),
  (405, "Customs, etiquette, folklore/Serial publications"),
  (406, "Customs, etiquette, folklore/Organizations & management"),
  (407, "Customs, etiquette, folklore/Education, research, related topics"),
  (408, "Customs, etiquette, folklore/Groups of people"),
  (409, "Customs, etiquette, folklore/Geographic treatment & biography"),
  (410, "Linguistics"),
  (411, "Writing systems of standard forms of languages"),
  (412, "Etymology of standard forms of languages"),
  (413, "Dictionaries of standard forms of languages"),
  (414, "Phonology & phonetics of standard forms of languages"),
  (415, "Grammar of standard forms of languages"),
  (417, "Dialectology & historical linguistics"),
  (418, "Standard usage (Prescriptive linguistics)"),
  (419, "Sign languages"),
  (420, "English & Old English languages"),
  (421, "Writing system, phonology, phonetics of standard English"),
  (422, "Etymology of standard English"),
  (423, "Dictionaries of standard English"),
  (425, "Grammar of standard English"),
  (427, "Historical & geographical variations, modern nongeographic variations of English"),
  (428, "Standard English usage (Prescriptive linguistics)"),
  (429, "Old English (Anglo-Saxon)"),
  (430, "German and related languages"),
  (431, "Writing systems, phonology, phonetics of standard German"),
  (432, "Etymology of standard German"),
  (433, "Dictionaries of standard German"),
  (435, "Grammar of standard German"),
  (437, "Historical & geographic variations, modern nongeographic variations of German"),
  (438, "Standard German usage (Prescriptive linguistics)"),
  (439, "Other Germanic languages"),
  (440, "French & related languages"),
  (441, "Writing systems, phonology, phonetics of standard French"),
  (442, "Etymology of standard French"),
  (443, "Dictionaries of standard French"),
  (445, "Grammar of standard French"),
  (447, "Historical and geographic variations, modern nongeographic variations of French"),
  (448, "Standard French usage (Prescriptive linguistics)"),
  (449, "Occitan Catalan, Franco-Provençal"),
  (450, "Italian, Romanian & related languages"),
  (451, "Writing systems, phonology, phonetics of standard Italian"),
  (452, "Etymology of standard Italian"),
  (453, "Dictionaries of standard Italian"),
  (455, "Grammar of standard Italian"),
  (457, "Historical & geographic variations, modern nongeographic variations of Italian"),
  (458, "Standard Italian usage (Prescriptive linguistics)"),
  (459, "Romanian, Rhaetian, Sardinian, Corsican"),
  (460, "Spanish, Portuguese, Galician"),
  (461, "Writing systems, phonology, phonetics of standard Spanish"),
  (462, "Etymology of standard Spanish"),
  (463, "Dictionaries of standard Spanish"),
  (465, "Grammar of standard Spanish"),
  (467, "Historical & geographic variations, modern nongeographic variations of Spanish"),
  (468, "Standard Spanish usage (Prescriptive linguistics)"),
  (469, "Portuguese"),
  (470, "Latin & related Italic languages"),
  (471, "Writing systems, phonology, phonetics of classical Latin"),
  (472, "Etymology of classical Latin"),
  (473, "Dictionaries of classical Latin"),
  (475, "Grammar of classical Latin"),
  (477, "Old, postclassical, Vulgar Latin"),
  (478, "Classical Latin usage (Prescriptive linguistics)"),
  (479, "Other Italic languages"),
  (480, "Classical Greek & related Hellenic languages"),
  (481, "Writing systems, phonology, phonetics of classical Greek"),
  (482, "Etymology of classical Greek"),
  (483, "Dictionaries of classical Greek"),
  (485, "Grammar of classical Greek"),
  (487, "Preclassical & postclassical Greek"),
  (488, "Classical Greek usage (Prescriptive linguistics)"),
  (489, "Other Hellenic languages"),
  (490, "Other languages"),
  (491, "East Indo-European & Celtic languages"),
  (492, "Afro-Asiatic languages"),
  (493, "Non-Semitic Afro-Asiatic languages"),
  (494, "Altic, Uralic, Hyperborean, Dravidian languages, miscellaneous languages of south Asia"),
  (495, "Languages of East & Southeast Asia"),
  (496, "African languages"),
  (497, "North American native languages"),
  (498, "South American native languages"),
  (499, "Non-Austronesian languages of Oceania, Austronesian languages, miscellaneous languages"),
  (500, "sciences"),
  (501, "Other languages/Philosophy & theory"),
  (502, "Other languages/Miscellany"),
  (503, "Other languages/Dictionaries, encyclopedias, concordances"),
  (505, "Other languages/Serial publications"),
  (506, "Other languages/Organizations & management"),
  (507, "Other languages/Education, research, related topics"),
  (508, "Other languages/Natural history"),
  (509, "Other languages/History, geographic treatment, biography"),
  (510, "Mathematics"),
  (511, "General principles of mathematics"),
  (512, "Algebra"),
  (513, "Arithmetic"),
  (514, "Topology"),
  (515, "Analysis"),
  (516, "Geometry"),
  (518, "Numerical analysis"),
  (519, "Probabilities & applied mathematics"),
  (520, "Astronomy & allied sciences"),
  (521, "Celestial mechanics"),
  (522, "Techniques, procedures, apparatus, equipment, materials"),
  (523, "Specific celestial bodies & phenomena"),
  (525, "Earth (Astronomical geography)"),
  (526, "Mathematical geography"),
  (527, "Celestial navigation"),
  (528, "Ephemerides"),
  (529, "Chronology"),
  (530, "Physics"),
  (531, "Classical mechanics"),
  (532, "Fluid mechanics"),
  (533, "Pneumatics (Gas mechanics)"),
  (534, "Sound & related vibrations"),
  (535, "Light & related radiation"),
  (536, "Heat"),
  (537, "Electricity & electronics"),
  (538, "Magnetism"),
  (539, "Modern physics"),
  (540, "Chemistry & allied sciences"),
  (541, "Physical chemistry"),
  (542, "Techniques, procedures, apparatus, equipment, materials"),
  (543, "Analytical chemistry"),
  (546, "Inorganic chemistry"),
  (547, "Organic chemistry"),
  (548, "Crystallography"),
  (549, "Mineralogy"),
  (550, "Earth sciences & geology"),
  (551, "Geology, hydrology, meteorology"),
  (552, "Petrology"),
  (553, "Economic geology"),
  (554, "Earth sciences of Europe"),
  (555, "Earth sciences of Asia"),
  (556, "Earth sciences of Africa"),
  (557, "Earth sciences of North America"),
  (558, "Earth sciences of South America"),
  (559, "Earth sciences of Australasia, Pacific Ocean islands, Atlantic Ocean islands, Arctic islands, Antarctica, extraterrestrial worlds"),
  (560, "Paleontology"),
  (561, "Paleobotany; fossil microorganisms"),
  (562, "Fossil invertebrates"),
  (563, "Miscellaneous fossil marine & seashore invertebrates"),
  (564, "Fossil Mollusca & Molluscoidea"),
  (565, "Fossil Arthropoda"),
  (566, "Fossil Chordata"),
  (567, "Fossil cold-blooded vertebrates"),
  (568, "Fossil Aves (birds)"),
  (569, "Fossil Mammalia"),
  (570, "Biology"),
  (571, "Physiology & related subjects"),
  (572, "Biochemistry"),
  (573, "Specific physiological systems in animals, regional histology & physiology in animals"),
  (575, "Specific parts of & physiological systems in plants"),
  (576, "Genetics and evolution"),
  (577, "Ecology"),
  (578, "Natural history of organisms & related subjects"),
  (579, "Natural history of microorganisms, fungi, algae"),
  (580, "Plants"),
  (581, "Specific topics in natural history of plants"),
  (582, "Plants noted for specific vegetative characteristics and flowers"),
  (583, "Magnoliopsida (Dicotyledones)"),
  (584, "Liliopsida (Monocotyledones)"),
  (585, "Pinophyta (Gymnosperms)"),
  (586, "Cryptogamia (Seedless plants)"),
  (587, "Pteridophyta"),
  (588, "Bryophyta"),
  (590, "Animals (Zoology)"),
  (591, "Specific topics in natural history of animals"),
  (592, "Invertebrates"),
  (593, "Miscellaneous marine & seashore invertebrates"),
  (594, "Mollusca & Molluscoidea"),
  (595, "Arthropoda"),
  (596, "Chordata"),
  (597, "Cold-blooded vertebrates"),
  (598, "Aves (Birds)"),
  (599, "Mammalia (Mammals)"),
  (600, "Technology"),
  (601, "Animals (Zoology)/Philosophy & theory"),
  (602, "Animals (Zoology)/Miscellany"),
  (603, "Animals (Zoology)/Dictionaries, encyclopedias, concordances"),
  (604, "Animals (Zoology)/Technical drawing, hazardous materials technology; groups of people"),
  (605, "Animals (Zoology)/Serial publications"),
  (606, "Animals (Zoology)/Organizations"),
  (607, "Animals (Zoology)/Education, research, related topics"),
  (608, "Animals (Zoology)/Patents"),
  (609, "Animals (Zoology)/History, geographic treatment, biography"),
  (610, "Medicine & health"),
  (611, "Human anatomy, cytology, histology"),
  (612, "Human physiology"),
  (613, "Personal health & safety"),
  (614, "Forensic medicine; incidence of injuries, wounds, disease; public preventive medicine"),
  (615, "Pharmacology and therapeutics"),
  (616, "Diseases"),
  (617, "Surgery, regional medicine, dentistry, ophthalmology, otology, audiology"),
  (618, "Gynecology, obstetrics, pediatrics, geriatrics"),
  (620, "Engineering"),
  (621, "Applied physics"),
  (622, "Mining & related operations"),
  (623, "Military & nautical engineering"),
  (624, "Civil engineering"),
  (625, "Engineering of railroads, roads"),
  (627, "Hydraulic engineering"),
  (628, "Sanitary engineering"),
  (629, "Other branches of engineering"),
  (630, "Agriculture"),
  (631, "Specific techniques; apparatus, equipment, materials"),
  (632, "Plant injuries, diseases, pests"),
  (633, "Field & plantation crops"),
  (634, "Orchards, fruits, forestry"),
  (635, "Garden crops (Horticulture)"),
  (636, "Animal husbandry"),
  (637, "Processing dairy & related products"),
  (638, "Insect culture"),
  (639, "Hunting, fishing, conservation, related technologies"),
  (640, "Home & family management"),
  (641, "Food & drink"),
  (642, "Meals & table service"),
  (643, "Housing & household equipment"),
  (644, "Household utilities"),
  (645, "Household furnishings"),
  (646, "Sewing, clothing, management of personal and family life"),
  (647, "Management of public households (Institutional housekeeping)"),
  (648, "Housekeeping"),
  (649, "Child rearing; home care of people with disabilities & illnesses"),
  (650, "Management & public relations"),
  (651, "Office services"),
  (652, "Processes of written communication"),
  (653, "Shorthand"),
  (657, "Accounting"),
  (658, "General management"),
  (659, "Advertising & public relations"),
  (660, "Chemical engineering"),
  (661, "Technology of industrial chemicals"),
  (662, "Technology of explosives, fuels, related products"),
  (663, "Beverage technology"),
  (664, "Food technology"),
  (665, "Technology of industrial oils, fats, waxes, gases"),
  (666, "Ceramic & allied technologies"),
  (667, "Cleaning, color, coating, related technologies"),
  (668, "Technology of other organic products"),
  (669, "Metallurgy"),
  (670, "Manufacturing"),
  (671, "Metalworking processes & primary metal products"),
  (672, "Iron, steel, other iron alloys"),
  (673, "Nonferrous metals"),
  (674, "Lumber processing, wood products, cork"),
  (675, "Leather & fur processing"),
  (676, "Pulp & paper technology"),
  (677, "Textiles"),
  (678, "Elastomers & elastomer products"),
  (679, "Other products of specific kinds of materials"),
  (680, "Manufacture for specific uses"),
  (681, "Precision instruments & other devices"),
  (682, "Small forge work (Blacksmithing)"),
  (683, "Hardware & household appliances"),
  (684, "Furnishings & home workshops"),
  (685, "Leather & fur goods, & related products"),
  (686, "Printing & related activities"),
  (687, "Clothing & accessories"),
  (688, "Other final products, & packaging technology"),
  (690, "Construction of buildings"),
  (691, "Building materials"),
  (692, "Auxiliary construction practices"),
  (693, "Construction in specific types of materials & for specific purposes"),
  (694, "Wood construction"),
  (695, "Roof covering"),
  (696, "Utilities"),
  (697, "Heating, ventilating, air-conditioning engineering"),
  (698, "Detail finishing"),
  (700, "Arts"),
  (701, "Philosophy & theory of fine & decorative arts"),
  (702, "Miscellany of fine & decorative arts"),
  (703, "Dictionaries, encyclopedias, concordances of fine & decorative arts"),
  (704, "Special topics in fine & decorative arts"),
  (705, "Serial publications of fine & decorative arts"),
  (706, "Organizations & management of fine & decorative arts"),
  (707, "Education, research, related topics of fine & decorative arts"),
  (708, "Galleries, museums, private collections of fine & decorative arts"),
  (709, "History, geographic treatment, biography"),
  (710, "Landscaping & area planning"),
  (711, "Area planning (Civic art)"),
  (712, "Landscape architecture (Landscape design)"),
  (713, "Landscape architecture of trafficways"),
  (714, "Water features in landscape architecture"),
  (715, "Woody plants in landscape architecture"),
  (716, "Herbaceous plants in landscape architecture"),
  (717, "Structures in landscape architecture"),
  (718, "Landscape design of cemeteries"),
  (719, "Natural landscapes"),
  (720, "Architecture"),
  (721, "Architectural materials & structural elements"),
  (722, "Architecture from earliest times to ca. 300"),
  (723, "Architecture from ca. 300 to 1399"),
  (724, "Architecture from 1400"),
  (725, "Public structures"),
  (726, "Buildings for religious & related purposes"),
  (727, "Buildings for educational & research purposes"),
  (728, "Residential & related buildings"),
  (729, "Design & decoration of structures & accessories"),
  (730, "Sculpture, ceramics, & metalwork"),
  (731, "Processes, forms, subjects of sculpture"),
  (732, "Sculpture from earliest times to ca. 500, sculpture of nonliterate peoples"),
  (733, "Greek, Etruscan, Roman sculpture"),
  (734, "Sculpture from ca. 500 to 1399"),
  (735, "Sculpture from 1400"),
  (736, "Carving & carvings"),
  (737, "Numismatics & sigillography"),
  (738, "Ceramic arts"),
  (739, "Art metalwork"),
  (740, "Graphic arts & decorative arts"),
  (741, "Drawing & drawings"),
  (742, "Perspective in drawing"),
  (743, "Drawing & drawings by subject"),
  (745, "Decorative arts"),
  (746, "Textile arts"),
  (747, "Interior decoration"),
  (748, "Glass"),
  (749, "Furniture & accessories"),
  (750, "Painting"),
  (751, "Techniques, procedures, apparatus, equipment, materials, forms"),
  (752, "Color"),
  (753, "Symbolism, allegory, mythology, legend"),
  (754, "Genre paintings"),
  (755, "Religion"),
  (757, "Human figures"),
  (758, "Nature, architectural subjects & cityscapes, other specific subjects"),
  (759, "History, geographic treatment, biography"),
  (760, "Printmaking & prints"),
  (761, "Relief processes (Block printing)"),
  (763, "Lithographic processes (Planographic processes)"),
  (764, "Chromolithography & serigraphy"),
  (765, "Metal engraving"),
  (766, "Mezzotinting, aquatinting, & related processes"),
  (767, "Etching & drypoint"),
  (769, "Prints"),
  (770, "Photography, computer art, cinematography"),
  (771, "Techniques, procedures, apparatus, equipment, materials"),
  (772, "Metallic salt processes"),
  (773, "Pigment processes of printing"),
  (776, "Computer art (Digital art)"),
  (777, "Cinematography & Videography"),
  (778, "Specific fields & special kinds of photography"),
  (779, "Photographic images"),
  (780, "Music"),
  (781, "General principles & musical forms"),
  (782, "Vocal music"),
  (783, "Music for single voices"),
  (784, "Instruments & Instrumental ensembles & their music"),
  (785, "Ensembles with only one instrument per part"),
  (786, "Keyboard, mechanical, electrophonic, percussion instruments"),
  (787, "Stringed instruments (Chordophones)"),
  (788, "Wind instruments (Aerophones)"),
  (790, "Recreational & performing arts"),
  (791, "Public performances"),
  (792, "Stage presentations"),
  (793, "Indoor games & amusements"),
  (794, "Indoor games of skill"),
  (795, "Games of chance"),
  (796, "Athletic & outdoor sports & games"),
  (797, "Aquatic & air sports"),
  (798, "Equestrian sports & animal racing"),
  (799, "Fishing, hunting, shooting"),
  (800, "Literature, rhetoric & criticism"),
  (801, "Recreational & performing arts/Philosophy & theory"),
  (802, "Recreational & performing arts/Miscellany"),
  (803, "Recreational & performing arts/Dictionaries, encyclopedias, concordances"),
  (805, "Recreational & performing arts/Serial publications"),
  (806, "Recreational & performing arts/Organizations & management"),
  (807, "Recreational & performing arts/Education, research, related topics"),
  (808, "Recreational & performing arts/Rhetoric & collections of literary texts from more than two literatures"),
  (809, "Recreational & performing arts/History, description, critical appraisal of more than two literatures"),
  (810, "American literature in English"),
  (811, "American poetry in English"),
  (812, "American drama in English"),
  (813, "American fiction in English"),
  (814, "American essays in English"),
  (815, "American speeches in English"),
  (816, "American letters in English"),
  (817, "American humor & satire in English"),
  (818, "American miscellaneous writings in English"),
  (820, "English & Old English literatures"),
  (821, "English Poetry"),
  (822, "English drama"),
  (823, "English fiction"),
  (824, "English essays"),
  (825, "English speeches"),
  (826, "English letters"),
  (827, "English humor & satire"),
  (828, "English miscellaneous writings"),
  (829, "Old English (Anglo-Saxon) literature"),
  (830, "German & related literatures"),
  (831, "German poetry"),
  (832, "German drama"),
  (833, "German fiction"),
  (834, "German essays"),
  (835, "German speeches"),
  (836, "German letters"),
  (837, "German humor & satire"),
  (838, "German miscellaneous writings"),
  (839, "Other Germanic literatures"),
  (840, "French & related literatures"),
  (841, "French poetry"),
  (842, "French drama"),
  (843, "French fiction"),
  (844, "French essays"),
  (845, "French speeches"),
  (846, "French letters"),
  (847, "French humor & satire"),
  (848, "French miscellaneous writings"),
  (849, "Occitan, Catalan, Franco-Provençal literatures"),
  (850, "Italian, Romanian & related literatures"),
  (851, "Italian poetry"),
  (852, "Italian drama"),
  (853, "Italian fiction"),
  (854, "Italian essays"),
  (855, "Italian speeches"),
  (856, "Italian letters"),
  (857, "Italian humor & satire"),
  (858, "Italian miscellaneous writings"),
  (859, "Literatures of Romanian, Rhaetian, Sardinian, Corsican languages"),
  (860, "Spanish & Portuguese literatures"),
  (861, "Spanish poetry"),
  (862, "Spanish drama"),
  (863, "Spanish fiction"),
  (864, "Spanish essays"),
  (865, "Spanish speeches"),
  (866, "Spanish letters"),
  (867, "Spanish humor & satire"),
  (868, "Spanish miscellaneous writings"),
  (869, "Literatures of Portuguese & Galician languages"),
  (870, "Latin & Italic literatures"),
  (871, "Latin poetry"),
  (872, "Latin dramatic poetry & drama"),
  (873, "Latin epic poetry & fiction"),
  (874, "Latin lyric poetry"),
  (875, "Latin speeches"),
  (876, "Latin letters"),
  (877, "Latin humor & satire"),
  (878, "Latin miscellaneous writings"),
  (879, "Literatures of other Italic languages"),
  (880, "Classical & modern Greek literatures"),
  (881, "Classical Greek poetry"),
  (882, "Classical Greek drama"),
  (883, "Classical Greek epic poetry & fiction"),
  (884, "Classical Greek lyric poetry"),
  (885, "Classical Greek speeches"),
  (886, "Classical Greek letters"),
  (887, "Classical Greek humor & satire"),
  (888, "Classical Greek miscellaneous writings"),
  (889, "Modern Greek literature"),
  (890, "Other literatures"),
  (891, "East Indo-European & Celtic literatures"),
  (892, "Afro-Asiatic literatures"),
  (893, "Non-Semitic Afro-Asiatic literatures"),
  (894, "Literatures of Altaic, Uralic, Hyperborean, Dravidian languages; literatures of miscellaneous languages of Southeast Asia"),
  (895, "Literatures of East & Southeast Asia"),
  (896, "African literatures"),
  (897, "Literatures of North American native languages"),
  (898, "Literatures of South American native languages"),
  (899, "Literatures of non-Austronesian languages of Oceania, of Austronesian languages, of miscellaneous languages"),
  (900, "History"),
  (901, "Literatures of other specific languages and language families/Philosophy & theory of history"),
  (902, "Literatures of other specific languages and language families/Miscellany of history"),
  (903, "Literatures of other specific languages and language families/Dictionaries, encyclopedias, concordances of history"),
  (904, "Literatures of other specific languages and language families/Collected accounts of events"),
  (905, "Literatures of other specific languages and language families/Serial publications of history"),
  (906, "Literatures of other specific languages and language families/Organizations & management of history"),
  (907, "Literatures of other specific languages and language families/Education, research, related topics of history"),
  (908, "Literatures of other specific languages and language families/History with respect to groups of people"),
  (909, "Literatures of other specific languages and language families/World history"),
  (910, "Geography & travel"),
  (911, "Historical geography"),
  (912, "Graphic representations of surface of earth and of extraterrestrial worlds"),
  (913, "Geography of & travel in ancient world"),
  (914, "Geography of & travel in Europe"),
  (915, "Geography of & travel in Asia"),
  (916, "Geography of & travel in Africa"),
  (917, "Geography of & travel in North America"),
  (918, "Geography of & travel in South America"),
  (919, "Geography of & travel in Australasia, Pacific Ocean islands, Atlantic Ocean islands, Arctic islands, Antarctica, & on extraterrestrial worlds"),
  (920, "Biography, genealogy"),
  (929, "Biography, genealogy, insignia/Genealogy, names, insignia"),
  (930, "History of ancient world to ca. 499"),
  (931, "China to 420"),
  (932, "Egypt to 640"),
  (933, "Palestine to 70"),
  (934, "South Asia to 647"),
  (935, "Mesopotamia to 637 & Iranian Plateau to 637"),
  (936, "Europe north & west of Italian Peninsula to ca. 499"),
  (937, "Italian Peninsula to 476 & adjacent territories to 476"),
  (938, "Greece to 323"),
  (939, "Other parts of ancient world"),
  (940, "History of Europe"),
  (941, "British Isles"),
  (942, "England & Wales"),
  (943, "Germany & neighboring central European countries"),
  (944, "France & Monaco"),
  (945, "Italy, San Marino, Vatican City, Malta"),
  (946, "Spain, Andorra, Gibraltar, Portugal"),
  (947, "Russia & neighboring east European countries"),
  (948, "Scandinavia"),
  (949, "Other parts of Europe"),
  (950, "History of Asia"),
  (951, "China & adjacent areas"),
  (952, "Japan"),
  (953, "Arabian Peninsula & adjacent areas"),
  (954, "India & neighboring south Asian countries;"),
  (955, "Iran"),
  (956, "Middle East (Near East)"),
  (957, "Siberia (Asiatic Russia)"),
  (958, "Central Asia"),
  (959, "Southeast Asia"),
  (960, "History of Africa"),
  (961, "Tunisia & Libya"),
  (962, "Egypt, Sudan, South Sudan"),
  (963, "Ethiopia & Eritrea"),
  (964, "Morocco, Ceuta, Melilla Western Sahara, Canary Islands"),
  (965, "Algeria"),
  (966, "West Africa & offshore islands"),
  (967, "Central Africa & offshore islands"),
  (968, "Republic of South Africa & neighboring southern African countries"),
  (969, "South Indian Ocean islands"),
  (970, "History of North America"),
  (971, "Canada"),
  (972, "Mexico, Central America, West Indies, Bermuda"),
  (973, "United States"),
  (974, "Northeastern United States (New England & Middle Atlantic states)"),
  (975, "Southeastern United States (South Atlantic states)"),
  (976, "South central United States"),
  (977, "North central United States"),
  (978, "Western United States"),
  (979, "Great Basin & Pacific Slope region of United States"),
  (980, "History of South America"),
  (981, "Brazil"),
  (982, "Argentina"),
  (983, "Chile"),
  (984, "Bolivia"),
  (985, "Peru"),
  (986, "Colombia & Ecuador"),
  (987, "Venezuela"),
  (988, "Guiana"),
  (989, "Paraguay & Uruguay"),
  (990, "History of other areas"),
  (993, "New Zealand"),
  (994, "Australia"),
  (995, "New Guinea & neighboring countries of Melanesia"),
  (996, "Polynesia & other Pacific Ocean islands"),
  (997, "Atlantic Ocean islands"),
  (998, "Arctic islands & Antarctica"),
  (999, "Extraterrestrial worlds");